# Generated by Django 4.2.7 on 2024-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("post_by", models.CharField(max_length=255)),
                ("count_view", models.IntegerField(default=0)),
            ],
        ),
    ]
