# Generated by Django 4.2.7 on 2024-11-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="New",
        ),
    ]
